name: itinereo
description: >
  Itinereo Ã¨ un'app Flutter che consente agli utenti di registrare esperienze di viaggio 
  sotto forma di voci di diario geolocalizzate, con immagini, date e itinerari generati automaticamente.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  geolocator: ^14.0.0
  firebase_storage: ^12.4.5
  uuid: ^4.5.1
  path_provider: ^2.1.5
  path: ^1.9.1
  firebase_app_check: ^0.3.2+5
  http: ^1.4.0
  sqflite: ^2.3.0
  intl: ^0.18.1 
  permission_handler: ^12.0.0+1
  device_info_plus: ^10.0.0
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  firebase_ai: ^2.0.0
  mime: ^2.0.0
  google_maps_flutter: ^2.12.2
  flutter_dotenv: ^5.2.1
  connectivity_plus: ^6.1.4
  smooth_page_indicator: ^1.2.1
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15
  mockito: ^5.4.6
  build_runner: ^2.4.15
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo_splash.png
  android: true
  android_gravity: center
  fullscreen: true

  android_12:
    color: "#FFFFFF"
    image: assets/images/logo_splash.png
    icon_background_color: "#FFFFFF"
    android_gravity: center
